### ISSUE TITLE
FAIL: test_docs_page (__main__.WebPageBrowsing)

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slateci.github.io#126]
Getting the following error:
```shell
======================================================================
FAIL: test_docs_page (__main__.WebPageBrowsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/main.py", line 155, in test_docs_page
    docs_page.iterate_links_doc_content(linkL1, linkL2)
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/page.py", line 154, in iterate_links_doc_content
    assert self.is_page_valid()
AssertionError

----------------------------------------------------------------------
Ran 6 tests in 206.988s

FAILED (failures=1)
```

**Comment by adamhgriffith-uofu** [comment]
After modifying the test code to tell me what the broken link was, determined it to be https://github.com/slateci/slate-catalog/blob/master/incubator/osg-frontier-squid/templates/fluentBitConfig.yaml on https://slateci.io/docs/apps/features.html.
