### ISSUE TITLE
Integration tests: selenium.common.exceptions.TimeoutException

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slateci.github.io#185]
Sometimes we encounter timeout errors in the Integration tests (e.g. from [Add example logs, fix a typo (#184) #107](https://github.com/slateci/slateci.github.io/actions/runs/3332020054):
```shell
======================================================================
ERROR: test_comm_page (__main__.WebPageBrowsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/main.py", line 210, in test_comm_page
    comm_page.wait_for_page_loaded()
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/page.py", line 211, in wait_for_page_loaded
    WebDriverWait(self.driver, 20).until(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5585a80722c3 <unknown>
#1 0x5585a7e7b83a <unknown>
...
...
```
 I believe this is because the Integration test workflow is running before the GitHub pages workflow is done publishing the new site content. Both work workflows trigger from push events to `master` so let's try a `workflow_run` event for the Integration Tests (see [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) for more details.

**Comment by adamhgriffith-uofu** [comment]
Changing when the tests ran did not help. Created https://github.com/slateci/slateci-unit-tests/issues/14 to track further debugging.
