### ISSUE TITLE
Integration tests consistently fail on test_comm_page()

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slateci.github.io#214]
Test runs like [Integration Tests #128](https://github.com/slateci/slateci.github.io/actions/runs/3943201489) seem to consistently fail at:
```shell
======================================================================
ERROR: test_comm_page (__main__.WebPageBrowsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/main.py", line 210, in test_comm_page
    comm_page.wait_for_page_loaded()
  File "/home/runner/work/slateci.github.io/slateci.github.io/slateci-unit-tests/page.py", line 211, in wait_for_page_loaded
    WebDriverWait(self.driver, 20).until(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563274dfd2a3 <unknown>
...
```
when automatically executed using the following event in `.github/workflows/integration-tests.yml`:
```yaml
on:
  workflow_run:
    workflows:
      - pages-build-deployment
    types:
      - completed
```
Repeating the run creates a successful outcome. My guess is that the integration tests are being run while GitHub Pages is still deploying things.

Let's try adding an explicit wait into the workflow file? Maybe that'll help.

**Comment by adamhgriffith-uofu** [comment]
Still failing. Re-opening.

**Comment by adamhgriffith-uofu** [comment]
Weird. Running this locally worked.
```shell
 podman run -it -v $PWD:/opt/project hub.opensciencegrid.org/slate/python-chromedriver-selenium:3.9-alpine python main.py
```

**Comment by adamhgriffith-uofu** [comment]
The following work locally but not on GitHub:
```
INFO     Community Page: Papers and Presentations
INFO     Community Page: Visit our YouTube Channel
```
